### ISSUE TITLE
when db password=5pO@vQW$FgFoN2w@, install zentao failed

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#593]
**Describe the bug**

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`zt_xdji8`' at line 1
```

- $ or @ make it?

**Comment by qiaofeng1227** [comment]
1. The reason for zentao installation failure is not due to the use of complex passwords“5pO@vQW$FgFoN2w@", I can use this password to successfully rebuild it

2. The reason for zentao's failure is that the application is named zt_xxxx. If this name is used, even if the password is all numbers and English, it will still fail

3. Modify the database name to zentao based on SQL error messages and the database name related to zt_xxxx to initialize normally

**Comment by chendelin1982** [comment]
DB_NAME change to zentao
